spring:
  mvc:
    static-path-pattern: /**

  resources:
    #默认路径为static
    static-locations: classpath:/static/

  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3000ms


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shilei.springbootdemo.entity